# Site settings
title: "Ziang Ye"
description: "LLM Agents, Long-Horizon Reasoning, and Self-Evolving Agents"
url: "https://whi497.github.io" # Your GitHub Pages domain
baseurl: "/leaf.github.io" # The repository/subdirectory name

# Author info
author:
  name: "Ziang Ye"
  email: "yza03@mail.ustc.edu.cn"
  phone: "+86 176 7108 8468"
  github: "whi497"
  scholar: "https://scholar.google.com/citations?user=o3TlNEUAAAAJ&hl=en"
  # twitter: "your_handle"

# Build settings
markdown: kramdown
highlighter: rouge

# Permalink style for blog posts
permalink: /writings/:year/:month/:day/:title/

# Exclude from build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
